# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Porkbun < Formula
  desc "CLI for the Porkbun domain registrar API"
  homepage "https://github.com/twt--/porkbun-cli"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/twt--/porkbun-cli/releases/download/v0.0.1/porkbun-cli_0.0.1_darwin_amd64.tar.gz"
      sha256 "29279913450b89376b39266657ba7b3d1474a07c03003ed88d9957ed1e97c402"

      define_method(:install) do
        bin.install "porkbun"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/twt--/porkbun-cli/releases/download/v0.0.1/porkbun-cli_0.0.1_darwin_arm64.tar.gz"
      sha256 "16139272d08f61eabf739051652c1236e561035d6af3f5ed974df1cc313604bc"

      define_method(:install) do
        bin.install "porkbun"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/twt--/porkbun-cli/releases/download/v0.0.1/porkbun-cli_0.0.1_linux_amd64.tar.gz"
      sha256 "d56594f248c35f0b8d2ad6a2f9e034e0156993acb12fd0143ec236df6569bda9"
      define_method(:install) do
        bin.install "porkbun"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/twt--/porkbun-cli/releases/download/v0.0.1/porkbun-cli_0.0.1_linux_arm64.tar.gz"
      sha256 "fc130fc3c9d033a7012eaaa2cffda7a05af8101816a96ea3af4733727e976672"
      define_method(:install) do
        bin.install "porkbun"
      end
    end
  end
end
