# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Porkbun < Formula
  desc "CLI for the Porkbun domain registrar API"
  homepage "https://github.com/twt--/porkbun-cli"
  version "0.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/twt--/porkbun-cli/releases/download/v0.0.1/porkbun-cli_0.0.1_darwin_amd64.tar.gz"
      sha256 "b6af03ca0c120a6590bf08406e1640aff482a601f1f2955c9b8328858f77ba4a"

      define_method(:install) do
        bin.install "porkbun"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/twt--/porkbun-cli/releases/download/v0.0.1/porkbun-cli_0.0.1_darwin_arm64.tar.gz"
      sha256 "0511ceb6a66620d2bda2f41a9c4963adb5bbbb722bd37407851300bd3deb4e63"

      define_method(:install) do
        bin.install "porkbun"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/twt--/porkbun-cli/releases/download/v0.0.1/porkbun-cli_0.0.1_linux_amd64.tar.gz"
      sha256 "cf7df4a98f5185978d35ea374208d12a7b614cd31c4a18df02f19388dd82fba8"
      define_method(:install) do
        bin.install "porkbun"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/twt--/porkbun-cli/releases/download/v0.0.1/porkbun-cli_0.0.1_linux_arm64.tar.gz"
      sha256 "b0bce89a15840b3fafe0bb13a323b31f5dbdb1751a11c59c138a71c8ebef238c"
      define_method(:install) do
        bin.install "porkbun"
      end
    end
  end
end
